### ISSUE TITLE
Mushrooms spawn on the roof of the nether

### ISSUE THREAD

**Issue by FewerFlaws** [DawnTeamMC/WildExplorer#10]
Although this is a minor issue, these mushrooms definitely don't have to be here and ought not to be showing up on minimaps that give a view from the sky =]
![2020-12-27_03 14 25](https://user-images.githubusercontent.com/75643699/103169606-25658500-47f2-11eb-8acc-4c5053baad49.png)

**Comment by Hugman76** [comment]
I believe this is already in issue with vanilla mushrooms?

**Comment by Dhranios** [comment]
Yeah, they do, this is a bug in the base game, not the mod.
