### ISSUE TITLE
Trees do not check for space before growing

### ISSUE THREAD

**Issue by FewerFlaws** [DawnTeamMC/WildExplorer#12]
Trees in vanilla [check for space](https://minecraft.gamepedia.com/Sapling#Growing_trees) above before growing.  These ones don't seem to do that =P

![2020-12-28_03 27 56](https://user-images.githubusercontent.com/75643699/103211401-f1a36180-48bc-11eb-8a71-ae9125702365.png)

**Comment by Hugman76** [comment]
The vanilla trees do not do that either ![image](https://user-images.githubusercontent.com/36963654/104090919-43af9400-527a-11eb-9ede-cf6c23430a90.png)
