### ISSUE TITLE
Wild Explorer crashes the game.

### ISSUE THREAD

**Issue by KirbyKid256** [DawnTeamMC/WildExplorer#2]
I was surprised no one brought this up yet, but Wild Explorer crashes Minecraft. I tried it in both 1.16.2 and 1.16.3. I tried 1.16.3 because your other mods are compatible with 1.16.3. And it still crashed on both versions.
[crash-2020-09-13_16.12.09-client.txt](https://github.com/DawnTeamMC/WildExplorer/files/5215034/crash-2020-09-13_16.12.09-client.txt)

While I'm here, I would also like to point out that Mubble crashes with Optifine. That one isn't such a big deal to me right now, so I'll leave it at that.

**Comment by Hugman76** [comment]
### Thanks for the report!
However, this bug is now outdated (Wild Explorer is on version 1.0-pre1 and Fabric API on 0.20.2+build.402-1.16 in your log)
Please try again with newer versions of the mods!
