### ISSUE TITLE
Registry remapping failed: Received ID map.... can't connect!

### ISSUE THREAD

**Issue by Animarix** [DawnTeamMC/WildExplorer#8]
Hello, 

I downloaded all of the fabrics 3 from curseforge in order to join a friends server.

Download went well and everything but when I tried to join I keep getting this message: 

Registry remapping failed: Received ID map for minecraft:block contains IDs unknown to the receiver
- wild_explorer:amaranth_roots
-wild_explorer:amaranth_dylium
-wild_explorer:amaranth_wart_block

server works for everyone else

**Comment by Secretlyalien** [comment]
I have the same issue and I went to fabric's server in discord and they told me the modpack has a different version from the server, but they didnt really give a fix

**Comment by Hugman76** [comment]
This means that the server has an outdated version of the mod. Either downgrade to their version, or wait for the server/ask the administrator to update to the latest versions.

**Comment by Secretlyalien** [comment]
I'm the server owner tho, but its in one mod in the whole modpack so its hard to like fix that and I think theyre the same version anyways
